name: Build and Upload ELF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \

      # Install the GNU Arm toolchain
      - name: Install GNU Arm Toolchain
        run: |
          wget -O /tmp/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
          sudo mkdir -p /opt/arm-gnu-toolchain
          sudo tar -xvf /tmp/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz -C /opt/arm-gnu-toolchain --strip-components 1
          rm /tmp/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
          echo "export PATH=/opt/arm-gnu-toolchain/bin:\$PATH" >> $GITHUB_ENV

      # Compile the project
      - name: Compile the project
        run: |
          cmake -B build -S .
          cmake --build build

      # Upload the compiled ELF file as an artifact
      - name: Upload ELF artifact
        uses: actions/upload-artifact@v3
        with:
          name: MirkoController.elf
          path: build/MirkoController.elf